// Generated by CoffeeScript 1.3.3
// jquery.linkem.js
// Copyright Michael Hanson
// https://github.com/mybuddymichael/jquery-linkem

(function() {
  var $;

  $ = this.jQuery;

  $.fn.linkem = function() {
    var _this = this;
    return this.on("keydown keyup mousedown mouseup", function() {
      return _this.text(_this.val());
    });
  };

  return this;

}).call(this);
